# name: Update packages

# on:
#   schedule:
#     - cron: "*/30 * * * *"
#   push:
#     branches: main
#   workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-scheduled
#   cancel-in-progress: false

# defaults:
#   run:
#     shell: bash -l {0}

# permissions:
#   contents: read
#   id-token: write

# jobs:
#   update_packages:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Install Conda environment with Micromamba
#         uses: mamba-org/setup-micromamba@v2
#         with:
#           environment-file: environment.yml

#       - name: Update mirror
#         run: python -m script
